- name: set hosts
  lineinfile:
    path: /etc/hosts
    regexp: ^127.0.1.1
    line: 127.0.1.1 {{ hostname }}

- name: set /etc/hostname
  copy:
    dest: "/etc/hostname"
    content: "{{ hostname }}\n"
  notify: set hostname

- name: apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
     - samba
     - winbind

- name: silent port 53
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: ^#DNSStubListener
    line: "DNSStubListener=no"
  notify: restart resolved

- name: remove smb.conf
  command: rm /etc/samba/smb.conf

- name: dcpromo
  command:
    samba-tool domain provision 
    --domain {{ samba_domain }} 
    --host-name {{ samba_host_name }}
    --adminpass {{ samba_adminpass }}
    --krbtgtpass {{ samba_krbtgtpass }}
    --realm {{ samba_realm }}
