- name: set hosts
  lineinfile:
    path: /etc/hosts
    regexp: ^127.0.1.1
    line: 127.0.1.1 {{ hostname }}

- name: set /etc/hostname
  copy:
    dest: "/etc/hostname"
    content: "{{ hostname }}\n"

- name: set hostname
  command: hostname -b {{ hostname }}

- name: silent port 53
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: ^#DNSStubListener
    line: "DNSStubListener=no"

- name: link
  file:
    src: "/run/systemd/resolve/resolv.conf"
    dest: "/etc/resolv.conf"
    state: link
    force: yes

- name: restart resolved
  service: name=systemd-resolved state=restarted

- name: apt packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
     - samba
     - winbind

- name: stop winbind
  service: name=winbind status=stopped enabled=no

- name: remove smb.conf
  file: 
    path: "/etc/samba/smb.conf"
    state: absent

- name: stop smbd
  service: name=smbd state=stopped enabled=no

- name: dcpromo
  command:
    samba-tool domain provision 
    --domain {{ samba_domain }} 
    --host-name {{ samba_host_name }}
    --adminpass {{ samba_adminpass }}
    --krbtgtpass {{ samba_krbtgtpass }}
    --realm {{ samba_realm }}

- name: samba-ad-dc
  service: name=samba-ad-dc enabled=yes state=started masked=no
